version: '3'

services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file: ".env"
    networks:
      - back
  db:
    image: postgres
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - back

volumes:
  db-data:
  
networks: 
  back: